# Config override for deployment
version: '3'

volumes:
  arianna_diary_mongodb_prod:
    external: true

services:
  api:
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=8779"
    - "traefik.frontend.rule=Host:arianna.digit.srl"
    - "traefik.frontend.entryPoints=http,https"
    - "traefik.frontend.redirect.entryPoint=https"

  mongo:
    volumes:
    - arianna_diary_mongodb_prod:/data/db:rw
    ports:
    - "8125:27017"

  fathom:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.protocol=http"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:fathom.arianna.digit.srl"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.redirect.entryPoint=https"
